### ISSUE TITLE
Docs update

### ISSUE THREAD

**Issue by probablykabari** [iamspydey/tailwind_cli#10]
https://docs.devsbuddy.com/tailwind-cli/installation.html#publish-the-config-file

This leads to the following error:
```
❯ flutter pub run tailwind_cli:init
Deprecated. Use `dart run` instead.
Building package executable... (2.1s)
Failed to build tailwind_cli:init:
```

The new working command is `dart run tailwind_cli:init`

(I'm not sure where the docs are so I didn't make a PR myself.)

**Comment by thedevsbuddy** [comment]
Hello @probablykabari 
Thank you for pointing out the issue. Can you please clear what version of flutter and dart SDK is throwing this error so I can produce it in my end and update it. 

As I checked in my setup it is working fine and not throwing any error. My setup version info is provided below:

I ran:
```
flutter --version
```

Output:
```
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (3 months ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
```

I also tried running in below environment:
```
Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792 (5 weeks ago) • 2023-06-13 15:51:02 -0700
Engine • revision 45f6e00911
Tools • Dart 3.0.5 • DevTools 2.23.1
```

It is working fine on all the environment.
