### ISSUE TITLE
flutter pub run tailwind_cli:build.  Null check operator used on a null value

### ISSUE THREAD

**Issue by dulguuned** [iamspydey/tailwind_cli#8]
flutter pub run tailwind_cli:build
Utilities Generated successfully!
Tailwind file generated successfully!
Utilities Generated successfully!
Pubspec YAML file generated successfully!
Unhandled exception:
Null check operator used on a null value
#0      processColors.<anonymous closure> (package:tailwind_cli/src/MixinsGenerator.dart:118:33)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#2      processColors (package:tailwind_cli/src/MixinsGenerator.dart:69:10)
#3      generateColorMixin (package:tailwind_cli/src/MixinsGenerator.dart:51:76)
#4      generate (package:tailwind_cli/src/MixinsGenerator.dart:18:9)
#5      main (file:///Users/enkhdulguun/.pub-cache/hosted/pub.dev/tailwind_cli-0.5.1/bin/build.dart:14:19)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
pub finished with exit code 255

**Comment by dulguuned** [comment]
<img width="299" alt="Screenshot 2023-02-09 at 01 43 34" src="https://user-images.githubusercontent.com/10085623/217609994-0fbbc2a5-1e98-4009-97fd-6b6035e831c1.png">
<img width="583" alt="Screenshot 2023-02-09 at 01 44 47" src="https://user-images.githubusercontent.com/10085623/217610160-18eb0b5f-f4e2-498b-9214-723110d6bf4e.png">
<img width="468" alt="Screenshot 2023-02-09 at 01 43 53" src="https://user-images.githubusercontent.com/10085623/217610231-ef9be42b-b2ae-400c-b433-6ea617a7c1b1.png">

TwContextExtension.dart not created

**Comment by thedevsbuddy** [comment]
@dulguuned  Fixed the issue with [Commit](https://github.com/thedevsbuddy/tailwind_cli/commit/1a191b74a3d73f84af45e7be1733716f137b941b)
