### ISSUE TITLE
TwText null check operator used on a null value

### ISSUE THREAD

**Issue by dulguuned** [iamspydey/tailwind_cli#9]
<img width="844" alt="Screenshot 2023-02-10 at 00 45 01" src="https://user-images.githubusercontent.com/10085623/217881095-a95fe4cf-c4b9-4154-a256-932503c1e78d.png">

**Comment by thedevsbuddy** [comment]
@dulguuned Can you please provide the complete code in which you got the error? So I can check which part the error is in.

**Comment by dulguuned** [comment]
if i just do           "Text".isText.render()

**Comment by thedevsbuddy** [comment]
@dulguuned I tested with the same code `"Some text".isText.render()` you provided it is working fine and not having any issues. 

Also, I tested with the `fontFamily` method it is working fine.

`"Some text".isText.fontFamily(GoogleFonts.workSans().fontFamily).render()`

**Comment by safwanolaimat** [comment]
![image](https://github.com/thedevsbuddy/tailwind_cli/assets/12313848/4e13ee30-46b7-4e05-bf4a-d6103e1a7154)

![image](https://github.com/thedevsbuddy/tailwind_cli/assets/12313848/af6a30ae-6fc2-4743-b0d8-51d2ae3b0bb6)

@thedevsbuddy

**Comment by thedevsbuddy** [comment]
@safwanolaimat Can you please post the usage of this Widget from where you got this `Exception`?

**Comment by safwanolaimat** [comment]
@thedevsbuddy 
You can get this error at basic app
Just create new project and follow the insruction to install your package 
Then use `"hello world".isText.render()`

Can you upload an example working project ?

What is your dart & flutter versions?

**Comment by thedevsbuddy** [comment]
Finally, after digging deep into the code layer I found that there is no issue with the `TwText` widget itself or the package.

The main issue is in documentation as I forgot to add must needed configuration option in the installation section of the doc 

For those who got the error please configure it as follows: 
- In your `main()` method:
    - Make it async and add this inside it 
```dart
 void main() async {
  await TwService.init(); // Add this line
  runApp(const MyApp());
}
```
- And inside your `MaterialApp` add `TwService.appKey` in the `MaterialApp` key property.
Example: 
```dart
return MaterialApp(
  key: TwService.appKey,
  //... rest properties
);
```

This will fix the error and I will add this configuration option to the documentation ASAP.

Please follow [https://docs.devsbuddy.com/tailwind-cli/installation.html#configure-your-app-to-use-tailwind](https://docs.devsbuddy.com/tailwind-cli/installation.html#configure-your-app-to-use-tailwind) to configure your app to use Tailwind Properly.

Thanks.
